/* linux/arch/arm/mach-exynos/include/mach/gpio-meizu.h
 *
 * Copyright (C) 2013 Meizu Technology Co.Ltd, Zhuhai, China
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc.,
 *
 * Revision History
 *
 * Author: wangbo@meizu.com
 * Date:    2013-8-28
 *
 */

#ifndef _MEIZU_GPIO_H_
#define _MEIZU_GPIO_H_

#include <mach/gpio.h>

enum {
	/* external interrupt source*/
	MEIZU_PMIC_IRQ_INDEX = 0,
	MEIZU_TOUCH_IRQ_INDEX,
	MEIZU_KEYOFF_IRQ_INDEX,
	MEIZU_IR_IRQ_INDEX,
	MEIZU_BB_RST_IRQ_INDEX,
	MEIZU_IPC_TRIG_IRQ_INDEX,
	MEIZU_VBUS_DET_IRQ_INDEX,
	MEIZU_SRDY_IRQ_INDEX,
	MEIZU_MCU_IRQ_INDEX,
	MEIZU_PMIC_IRQ2_INDEX,
	MEIZU_USB_ID_IRQ_INDEX,
	MEIZU_IPC_HOST_WAKE_IRQ_INDEX,
	MEIZU_VOLUP_IRQ_INDEX,
	MEIZU_WIFI_IRQ_INDEX,
	MEIZU_FUELGAGE_IRQ_INDEX,
	MEIZU_USB_IRQ_INDEX,
	MEIZU_HOME_IRQ_INDEX,
	MEIZU_MIC_IRQ_INDEX,
	MEIZU_PMIC_RST_IRQ_INDEX,
	MEIZU_BT_HOSTWAKE_IRQ_INDEX,
	MEIZU_NFC_IRQ_INDEX,
	MEIZU_VOLDOWN_IRQ_INDEX,
	MEIZU_HDETEC_IRQ_INDEX,
	MEIZU_CODEC_IRQ_INDEX,

	/* led zone*/
	MEIZU_LED_ID1_INDEX,
	MEIZU_LED_ID2_INDEX,
	MEIZU_LED_ID3_INDEX,
	MEIZU_LED_ID4_INDEX,
	MEIZU_LED_ID5_INDEX,
	MEIZU_LED_ID6_INDEX,

	/* wifi and bluetooth zone */
	MEIZU_BT_RXD_INDEX,
	MEIZU_BT_TXD_INDEX,
	MEIZU_BT_CTS_INDEX,
	MEIZU_BT_RTS_INDEX,
	MEIZU_BT_REGON_INDEX,
	MEIZU_BT_HOST_WAKE_INDEX,
	MEIZU_BT_WAKE_INDEX,
	MEIZU_WL_REGON_INDEX,

	/* core select*/
	MEIZU_CORE_SEL_INDEX,

	/* arm core, int, g3d voltage control pin */
	MEIZU_GPIO_DVS1_INDEX,
	MEIZU_GPIO_DVS2_INDEX,
	MEIZU_GPIO_DVS3_INDEX,

	/* pmic buck sel */
	MEIZU_BUCK1_SEL_INDEX,
	MEIZU_BUCK2_SEL_INDEX,
	MEIZU_BUCK3_SEL_INDEX,
	MEIZU_BUCK4_SEL_INDEX,
	MEIZU_BUCK6_SEL_INDEX,

	/*sub pmic*/
	MEIZU_CHG_SDA_INDEX,
	MEIZU_CHG_SCL_INDEX,

	/* IR control */
	MEIZU_IR_PWEN_INDEX,
	MEIZU_IR_SDA_INDEX,
	MEIZU_IR_SCL_INDEX,

	/* COMPASS control */
	MEIZU_AKM_SDA_INDEX,
	MEIZU_AKM_SCL_INDEX,

	/* MCU control*/
	MEIZU_MCU_SDA_INDEX,
	MEIZU_MCU_SCL_INDEX,
	MEIZU_MCU_SDA_O_INDEX,
	MEIZU_MCU_SCL_O_INDEX,
	MEIZU_MCU_SLEEP_INDEX,
	MEIZU_MCU_RST_INDEX,
	MEIZU_MCU_BUSY_INDEX,

	/* version contorl*/
	MEIZU_VER_PIN0_INDEX,
	MEIZU_VER_PIN1_INDEX,
	MEIZU_VER_PIN2_INDEX,

	/* modem control */
	MEIZU_IPC_SLAVE_WAKEUP_INDEX,
	MEIZU_IPC_TRIGIN_INDEX,
	MEIZU_MODEM_ON_INDEX,
	MEIZU_BB_RST_INDEX,
	MEIZU_PMU_RST_INDEX,

	/* NFC control */
	MEIZU_NFC_WAKE_INDEX,
	MEIZU_NFC_REG_PU_INDEX,
	MEIZU_NFC_VSIM_REQ_INDEX,
	MEIZU_NFC_REQ_INDEX,
	MEIZU_NFC_SCL_INDEX,
	MEIZU_NFC_SDA_INDEX,

	/* GPS control*/
	MEIZU_GPS_PWR_ON_INDEX,
	MEIZU_GPS_CLK_REQ_INDEX,
	MEIZU_GPS_RXD_INDEX,
	MEIZU_GPS_TXD_INDEX,
	MEIZU_GPS_CTS_INDEX,
	MEIZU_GPS_RTS_INDEX,

	/* Fuelgage contorl */
	MEIZU_FUEL_SDA_INDEX,
	MEIZU_FUEL_SCL_INDEX,

	/* Accelerometer and Gyroscope*/
	MEIZU_GY_DEN_INDEX,
	MEIZU_G_INT1_INDEX,
	MEIZU_G_INT2_INDEX,
	MEIZU_A_INT1_INDEX,
	MEIZU_A_INT2_INDEX,

	/* Motor control*/
	MEIZU_MOTOR_PWM_INDEX,

	/* Touch Panel control*/
	MEIZU_TOUCH_RST_INDEX,
	MEIZU_TOUCH_SDA_INDEX,
	MEIZU_TOUCH_SCL_INDEX,

	/* ISP contorl*/
	/*
	* MAX77802 OUT35, VDD12_8MSEN
	*/
	MEIZU_ISP_VDD12_8MSEN_INDEX,
	MEIZU_ISP_RST_INDEX,

	/*
	* 24M clock to external ISP.
	*/
	MEIZU_ISP_XCLK_IN_INDEX,

	/*
	* IRQ from external ISP.
	*/
	MEIZU_ISP_IRQ_INDEX,
	MEIZU_ISP_I2CSDA_INDEX,
	MEIZU_ISP_I2CSCL_INDEX,
	MEIZU_ISP_SPI_CLK_INDEX,
	MEIZU_ISP_SPI_MOSI_INDEX,
	MEIZU_ISP_SPI_CS_INDEX,

	/* Audio control*/
	MEIZU_CODEC_AUEN_INDEX,
	MEIZU_CODEC_RST_INDEX,
	MEIZU_CODEC_SDA_INDEX,
	MEIZU_CODEC_SCL_INDEX,
	MEIZU_NOISE_CANCELLER_WAKE_INDEX,
	MEIZU_NOISE_CANCELLER_RST_INDEX,
	MEIZU_PA_SDA_INDEX,
	MEIZU_PA_SCL_INDEX,
	MEIZU_ES305B_SDA_INDEX,
	MEIZU_ES305B_SCL_INDEX,

	/* LCD control */
	MEIZU_LCD_5VEN_INDEX,
	MEIZU_LCD_N5VEN_INDEX,
	MEIZU_LCD_BIAS_SDA_INDEX,
	MEIZU_LCD_BIAS_SCL_INDEX,
	MEIZU_LCD_BL_SDA_INDEX,
	MEIZU_LCD_BL_SCL_INDEX,
	MEIZU_LCD_BL_EN_INDEX,
	MEIZU_LCD_ID_INDEX,
	MEIZU_LCD_RST_INDEX,
	MEIZU_LCD_TE_INDEX,
	MEIZU_LCD_HW_TE_INDEX,

	/* TF card contorl*/
	MEIZU_TF_CARD_EN_INDEX,

	/* EEPROM contorl*/
	MEIZU_EEPROM_WP_INDEX,
	MEIZU_EEPROM_SCL_INDEX,
	MEIZU_EEPROM_SDA_INDEX,
	MEIZU_SENSOR_SCL_INDEX,
	MEIZU_SENSOR_SDA_INDEX,

	/* factory mode define zone */
	MEIZU_GPIO_FACTORY_MODE_INDEX,
	MEIZU_GPIO_TEST_LED_INDEX,

	/* sc8803g MODEM control */
	MEIZU_GPIO_MODEM_POWER_ON_INDEX,
	MEIZU_GPIO_MODEM_RDY_INDEX,
	MEIZU_GPIO_AP_RDY_INDEX,
	MEIZU_GPIO_MODEM_RTS_INDEX,
	MEIZU_GPIO_AP_RTS_INDEX,
	MEIZU_GPIO_MODEM_RESEND_INDEX,
	MEIZU_GPIO_AP_RESEND_INDEX,
	MEIZU_GPIO_MODEM_ALIVE_INDEX,
	MEIZU_GPIO_MODEM_TO_AP1_INDEX,
	MEIZU_GPIO_MODEM_TO_AP2_INDEX,
	MEIZU_GPIO_AP_TO_MODEM1_INDEX,
	MEIZU_GPIO_AP_TO_MODEM2_INDEX,

	/*board id 321*/
	MEIZU_BOARD_ID1_INDEX,
	MEIZU_BOARD_ID2_INDEX,
	MEIZU_BOARD_ID3_INDEX,

	MAX_MEIZU_GPIO_INDEX,
};

#if defined(CONFIG_MACH_M65) || defined(CONFIG_MACH_M69)
#ifdef CONFIG_MACH_M65
#include "gpio-m65.h"
#endif
#ifdef CONFIG_MACH_M69
#include "gpio-m69.h"
#endif
#else
#error "Please Configure The Machine Version."
#endif

extern const unsigned short *meizu_gpio;

#define MEIZU_PMIC_IRQ				meizu_gpio[MEIZU_PMIC_IRQ_INDEX]
#define MEIZU_TOUCH_IRQ				meizu_gpio[MEIZU_TOUCH_IRQ_INDEX]
#define MEIZU_KEYOFF_IRQ			meizu_gpio[MEIZU_KEYOFF_IRQ_INDEX]
#define MEIZU_IR_IRQ				meizu_gpio[MEIZU_IR_IRQ_INDEX]
#define MEIZU_BB_RST_IRQ			meizu_gpio[MEIZU_BB_RST_IRQ_INDEX]
#define MEIZU_IPC_TRIG_IRQ			meizu_gpio[MEIZU_IPC_TRIG_IRQ_INDEX]
#define MEIZU_VBUS_DET_IRQ			meizu_gpio[MEIZU_VBUS_DET_IRQ_INDEX]
#define MEIZU_SRDY_IRQ				meizu_gpio[MEIZU_SRDY_IRQ_INDEX]
#define MEIZU_MCU_IRQ				meizu_gpio[MEIZU_MCU_IRQ_INDEX]
#define MEIZU_PMIC_IRQ2				meizu_gpio[MEIZU_PMIC_IRQ2_INDEX]
#define MEIZU_USB_ID_IRQ			meizu_gpio[MEIZU_USB_ID_IRQ_INDEX]
#define MEIZU_IPC_HOST_WAKE_IRQ			meizu_gpio[MEIZU_IPC_HOST_WAKE_IRQ_INDEX]
#define MEIZU_VOLUP_IRQ				meizu_gpio[MEIZU_VOLUP_IRQ_INDEX]
#define MEIZU_WIFI_IRQ				meizu_gpio[MEIZU_WIFI_IRQ_INDEX]
#define MEIZU_FUELGAGE_IRQ			meizu_gpio[MEIZU_FUELGAGE_IRQ_INDEX]
#define MEIZU_USB_IRQ				meizu_gpio[MEIZU_USB_IRQ_INDEX]
#define MEIZU_HOME_IRQ				meizu_gpio[MEIZU_HOME_IRQ_INDEX]
#define MEIZU_MIC_IRQ				meizu_gpio[MEIZU_MIC_IRQ_INDEX]
#define MEIZU_PMIC_RST_IRQ			meizu_gpio[MEIZU_PMIC_RST_IRQ_INDEX]
#define MEIZU_BT_HOSTWAKE_IRQ			meizu_gpio[MEIZU_BT_HOSTWAKE_IRQ_INDEX]
#define MEIZU_NFC_IRQ				meizu_gpio[MEIZU_NFC_IRQ_INDEX]
#define MEIZU_VOLDOWN_IRQ			meizu_gpio[MEIZU_VOLDOWN_IRQ_INDEX]
#define MEIZU_HDETEC_IRQ			meizu_gpio[MEIZU_HDETEC_IRQ_INDEX]
#define MEIZU_CODEC_IRQ				meizu_gpio[MEIZU_CODEC_IRQ_INDEX]
#define MEIZU_LED_ID1				meizu_gpio[MEIZU_LED_ID1_INDEX]
#define MEIZU_LED_ID2				meizu_gpio[MEIZU_LED_ID2_INDEX]
#define MEIZU_LED_ID3				meizu_gpio[MEIZU_LED_ID3_INDEX]
#define MEIZU_LED_ID4				meizu_gpio[MEIZU_LED_ID4_INDEX]
#define MEIZU_LED_ID5				meizu_gpio[MEIZU_LED_ID5_INDEX]
#define MEIZU_LED_ID6				meizu_gpio[MEIZU_LED_ID6_INDEX]
#define MEIZU_BT_RXD				meizu_gpio[MEIZU_BT_RXD_INDEX]
#define MEIZU_BT_TXD				meizu_gpio[MEIZU_BT_TXD_INDEX]
#define MEIZU_BT_CTS				meizu_gpio[MEIZU_BT_CTS_INDEX]
#define MEIZU_BT_RTS				meizu_gpio[MEIZU_BT_RTS_INDEX]
#define MEIZU_BT_REGON				meizu_gpio[MEIZU_BT_REGON_INDEX]
#define MEIZU_BT_HOST_WAKE			meizu_gpio[MEIZU_BT_HOST_WAKE_INDEX]
#define MEIZU_BT_WAKE				meizu_gpio[MEIZU_BT_WAKE_INDEX]
#define MEIZU_WL_REGON				meizu_gpio[MEIZU_WL_REGON_INDEX]
#define MEIZU_CORE_SEL				meizu_gpio[MEIZU_CORE_SEL_INDEX]
#define MEIZU_GPIO_DVS1				meizu_gpio[MEIZU_GPIO_DVS1_INDEX]
#define MEIZU_GPIO_DVS2				meizu_gpio[MEIZU_GPIO_DVS2_INDEX]
#define MEIZU_GPIO_DVS3				meizu_gpio[MEIZU_GPIO_DVS3_INDEX]
#define MEIZU_BUCK1_SEL				meizu_gpio[MEIZU_BUCK1_SEL_INDEX]
#define MEIZU_BUCK2_SEL				meizu_gpio[MEIZU_BUCK2_SEL_INDEX]
#define MEIZU_BUCK3_SEL				meizu_gpio[MEIZU_BUCK3_SEL_INDEX]
#define MEIZU_BUCK4_SEL				meizu_gpio[MEIZU_BUCK4_SEL_INDEX]
#define MEIZU_BUCK6_SEL				meizu_gpio[MEIZU_BUCK6_SEL_INDEX]
#define MEIZU_CHG_SDA				meizu_gpio[MEIZU_CHG_SDA_INDEX]
#define MEIZU_CHG_SCL				meizu_gpio[MEIZU_CHG_SCL_INDEX]
#define MEIZU_IR_PWEN				meizu_gpio[MEIZU_IR_PWEN_INDEX]
#define MEIZU_IR_SDA				meizu_gpio[MEIZU_IR_SDA_INDEX]
#define MEIZU_IR_SCL				meizu_gpio[MEIZU_IR_SCL_INDEX]
#define MEIZU_AKM_SDA				meizu_gpio[MEIZU_AKM_SDA_INDEX]
#define MEIZU_AKM_SCL				meizu_gpio[MEIZU_AKM_SCL_INDEX]
#define MEIZU_MCU_SDA				meizu_gpio[MEIZU_MCU_SDA_INDEX]
#define MEIZU_MCU_SCL				meizu_gpio[MEIZU_MCU_SCL_INDEX]
#define MEIZU_MCU_SDA_O				meizu_gpio[MEIZU_MCU_SDA_O_INDEX]
#define MEIZU_MCU_SCL_O				meizu_gpio[MEIZU_MCU_SCL_O_INDEX]
#define MEIZU_MCU_SLEEP				meizu_gpio[MEIZU_MCU_SLEEP_INDEX]
#define MEIZU_MCU_RST				meizu_gpio[MEIZU_MCU_RST_INDEX]
#define MEIZU_MCU_BUSY				meizu_gpio[MEIZU_MCU_BUSY_INDEX]
#define MEIZU_VER_PIN0				meizu_gpio[MEIZU_VER_PIN0_INDEX]
#define MEIZU_VER_PIN1				meizu_gpio[MEIZU_VER_PIN1_INDEX]
#define MEIZU_VER_PIN2				meizu_gpio[MEIZU_VER_PIN2_INDEX]
#define MEIZU_IPC_SLAVE_WAKEUP			meizu_gpio[MEIZU_IPC_SLAVE_WAKEUP_INDEX]
#define MEIZU_IPC_TRIGIN			meizu_gpio[MEIZU_IPC_TRIGIN_INDEX]
#define MEIZU_MODEM_ON				meizu_gpio[MEIZU_MODEM_ON_INDEX]
#define MEIZU_BB_RST				meizu_gpio[MEIZU_BB_RST_INDEX]
#define MEIZU_PMU_RST				meizu_gpio[MEIZU_PMU_RST_INDEX]
#define MEIZU_NFC_WAKE				meizu_gpio[MEIZU_NFC_WAKE_INDEX]
#define MEIZU_NFC_REG_PU			meizu_gpio[MEIZU_NFC_REG_PU_INDEX]
#define MEIZU_NFC_VSIM_REQ			meizu_gpio[MEIZU_NFC_VSIM_REQ_INDEX]
#define MEIZU_NFC_REQ				meizu_gpio[MEIZU_NFC_REQ_INDEX]
#define MEIZU_NFC_SCL				meizu_gpio[MEIZU_NFC_SCL_INDEX]
#define MEIZU_NFC_SDA				meizu_gpio[MEIZU_NFC_SDA_INDEX]
#define MEIZU_GPS_PWR_ON			meizu_gpio[MEIZU_GPS_PWR_ON_INDEX]
#define MEIZU_GPS_CLK_REQ			meizu_gpio[MEIZU_GPS_CLK_REQ_INDEX]
#define MEIZU_GPS_RXD				meizu_gpio[MEIZU_GPS_RXD_INDEX]
#define MEIZU_GPS_TXD				meizu_gpio[MEIZU_GPS_TXD_INDEX]
#define MEIZU_GPS_CTS				meizu_gpio[MEIZU_GPS_CTS_INDEX]
#define MEIZU_GPS_RTS				meizu_gpio[MEIZU_GPS_RTS_INDEX]
#define MEIZU_FUEL_SDA				meizu_gpio[MEIZU_FUEL_SDA_INDEX]
#define MEIZU_FUEL_SCL				meizu_gpio[MEIZU_FUEL_SCL_INDEX]
#define MEIZU_GY_DEN				meizu_gpio[MEIZU_GY_DEN_INDEX]
#define MEIZU_G_INT1				meizu_gpio[MEIZU_G_INT1_INDEX]
#define MEIZU_G_INT2				meizu_gpio[MEIZU_G_INT2_INDEX]
#define MEIZU_A_INT1				meizu_gpio[MEIZU_A_INT1_INDEX]
#define MEIZU_A_INT2				meizu_gpio[MEIZU_A_INT2_INDEX]
#define MEIZU_MOTOR_PWM				meizu_gpio[MEIZU_MOTOR_PWM_INDEX]
#define MEIZU_TOUCH_RST				meizu_gpio[MEIZU_TOUCH_RST_INDEX]
#define MEIZU_TOUCH_SDA				meizu_gpio[MEIZU_TOUCH_SDA_INDEX]
#define MEIZU_TOUCH_SCL				meizu_gpio[MEIZU_TOUCH_SCL_INDEX]
#define MEIZU_ISP_VDD12_8MSEN			meizu_gpio[MEIZU_ISP_VDD12_8MSEN_INDEX]
#define MEIZU_ISP_RST				meizu_gpio[MEIZU_ISP_RST_INDEX]
#define MEIZU_ISP_XCLK_IN			meizu_gpio[MEIZU_ISP_XCLK_IN_INDEX]
#define MEIZU_ISP_IRQ				meizu_gpio[MEIZU_ISP_IRQ_INDEX]
#define MEIZU_ISP_I2CSDA			meizu_gpio[MEIZU_ISP_I2CSDA_INDEX]
#define MEIZU_ISP_I2CSCL			meizu_gpio[MEIZU_ISP_I2CSCL_INDEX]
#define MEIZU_ISP_SPI_CLK			meizu_gpio[MEIZU_ISP_SPI_CLK_INDEX]
#define MEIZU_ISP_SPI_MOSI			meizu_gpio[MEIZU_ISP_SPI_MOSI_INDEX]
#define MEIZU_ISP_SPI_CS			meizu_gpio[MEIZU_ISP_SPI_CS_INDEX]
#define MEIZU_CODEC_AUEN			meizu_gpio[MEIZU_CODEC_AUEN_INDEX]
#define MEIZU_CODEC_RST				meizu_gpio[MEIZU_CODEC_RST_INDEX]
#define MEIZU_CODEC_SDA				meizu_gpio[MEIZU_CODEC_SDA_INDEX]
#define MEIZU_CODEC_SCL				meizu_gpio[MEIZU_CODEC_SCL_INDEX]
#define MEIZU_NOISE_CANCELLER_WAKE		meizu_gpio[MEIZU_NOISE_CANCELLER_WAKE_INDEX]
#define MEIZU_NOISE_CANCELLER_RST		meizu_gpio[MEIZU_NOISE_CANCELLER_RST_INDEX]
#define MEIZU_PA_SDA				meizu_gpio[MEIZU_PA_SDA_INDEX]
#define MEIZU_PA_SCL				meizu_gpio[MEIZU_PA_SCL_INDEX]
#define MEIZU_ES305B_SDA			meizu_gpio[MEIZU_ES305B_SDA_INDEX]
#define MEIZU_ES305B_SCL			meizu_gpio[MEIZU_ES305B_SCL_INDEX]
#define MEIZU_LCD_5VEN				meizu_gpio[MEIZU_LCD_5VEN_INDEX]
#define MEIZU_LCD_N5VEN				meizu_gpio[MEIZU_LCD_N5VEN_INDEX]
#define MEIZU_LCD_BIAS_SDA			meizu_gpio[MEIZU_LCD_BIAS_SDA_INDEX]
#define MEIZU_LCD_BIAS_SCL			meizu_gpio[MEIZU_LCD_BIAS_SCL_INDEX]
#define MEIZU_LCD_BL_SDA			meizu_gpio[MEIZU_LCD_BL_SDA_INDEX]
#define MEIZU_LCD_BL_SCL			meizu_gpio[MEIZU_LCD_BL_SCL_INDEX]
#define MEIZU_LCD_BL_EN				meizu_gpio[MEIZU_LCD_BL_EN_INDEX]
#define MEIZU_LCD_ID				meizu_gpio[MEIZU_LCD_ID_INDEX]
#define MEIZU_LCD_RST				meizu_gpio[MEIZU_LCD_RST_INDEX]
#define MEIZU_LCD_TE				meizu_gpio[MEIZU_LCD_TE_INDEX]
#define MEIZU_LCD_HW_TE				meizu_gpio[MEIZU_LCD_HW_TE_INDEX]
#define MEIZU_TF_CARD_EN			meizu_gpio[MEIZU_TF_CARD_EN_INDEX]
#define MEIZU_EEPROM_WP				meizu_gpio[MEIZU_EEPROM_WP_INDEX]
#define MEIZU_EEPROM_SCL			meizu_gpio[MEIZU_EEPROM_SCL_INDEX]
#define MEIZU_EEPROM_SDA			meizu_gpio[MEIZU_EEPROM_SDA_INDEX]
#define MEIZU_SENSOR_SCL			meizu_gpio[MEIZU_SENSOR_SCL_INDEX]
#define MEIZU_SENSOR_SDA			meizu_gpio[MEIZU_SENSOR_SDA_INDEX]
#define MEIZU_GPIO_FACTORY_MODE			meizu_gpio[MEIZU_GPIO_FACTORY_MODE_INDEX]
#define MEIZU_GPIO_TEST_LED			meizu_gpio[MEIZU_GPIO_TEST_LED_INDEX]
/* For  SC8803G */
#define MEIZU_GPIO_MODEM_POWER_ON		meizu_gpio[MEIZU_GPIO_MODEM_POWER_ON_INDEX]
#define MEIZU_GPIO_MODEM_RDY			meizu_gpio[MEIZU_GPIO_MODEM_RDY_INDEX]
#define MEIZU_GPIO_AP_RDY			meizu_gpio[MEIZU_GPIO_AP_RDY_INDEX]
#define MEIZU_GPIO_MODEM_RTS			meizu_gpio[MEIZU_GPIO_MODEM_RTS_INDEX]
#define MEIZU_GPIO_AP_RTS			meizu_gpio[MEIZU_GPIO_AP_RTS_INDEX]
#define MEIZU_GPIO_MODEM_RESEND			meizu_gpio[MEIZU_GPIO_MODEM_RESEND_INDEX]
#define MEIZU_GPIO_AP_RESEND			meizu_gpio[MEIZU_GPIO_AP_RESEND_INDEX]
#define MEIZU_GPIO_MODEM_ALIVE			meizu_gpio[MEIZU_GPIO_MODEM_ALIVE_INDEX]
#define MEIZU_GPIO_MODEM_TO_AP1			meizu_gpio[MEIZU_GPIO_MODEM_TO_AP1_INDEX]
#define MEIZU_GPIO_MODEM_TO_AP2			meizu_gpio[MEIZU_GPIO_MODEM_TO_AP2_INDEX]
#define MEIZU_GPIO_AP_TO_MODEM1			meizu_gpio[MEIZU_GPIO_AP_TO_MODEM1_INDEX]
#define MEIZU_GPIO_AP_TO_MODEM2			meizu_gpio[MEIZU_GPIO_AP_TO_MODEM2_INDEX]

/*Board id*/
#define MEIZU_BOARD_ID1				meizu_gpio[MEIZU_BOARD_ID1_INDEX]
#define MEIZU_BOARD_ID2				meizu_gpio[MEIZU_BOARD_ID2_INDEX]
#define MEIZU_BOARD_ID3				meizu_gpio[MEIZU_BOARD_ID3_INDEX]

#endif /* _MEIZU_GPIO_H_ */
