#ifndef __MS2R_CTRL_H__
#define __MS2R_CTRL_H__

/*
  *
  * This file is for our private ioctl command definition and enumeration
  * distinguish from samsung
  *
*/


/* 
  * for panorama capture
*/
#define V4L2_CID_CAMERA_PANO_CAPTURE    					(V4L2_CID_PRIVATE_BASE + 51) 
#define V4L2_CID_CAMERA_PANO_PICTURE_NUM 				(V4L2_CID_PRIVATE_BASE + 251) 
#define V4L2_CID_CAMERA_PANO_STATUS 						(V4L2_CID_PRIVATE_BASE + 252) 
#define V4L2_CID_CAMERA_TERMINATE_PANO 					(V4L2_CID_PRIVATE_BASE + 255)
#define V4L2_CID_CAMERA_PANO_READY 						(V4L2_CID_PRIVATE_BASE + 256)
#define V4L2_CID_CAMERA_PANO_DIRECTION 					(V4L2_CID_PRIVATE_BASE + 257)

/*
  * for face and smile detection
*/
#define V4L2_CID_CAMERA_SMILE_FACE_DETECTION 			(V4L2_CID_PRIVATE_BASE + 253) 
#define V4L2_CID_CAMERA_FACE_DET_NUM 					(V4L2_CID_PRIVATE_BASE + 254) 
#define V4L2_CID_CAMERA_FACE_DET_SELECT 					(V4L2_CID_PRIVATE_BASE + 258) 
#define V4L2_CID_CAMERA_SELECTED_FACE_LOCATION 			(V4L2_CID_PRIVATE_BASE + 259) 
#define V4L2_CID_CAMERA_SELECTED_FACE_SIZE 				(V4L2_CID_PRIVATE_BASE + 260) 
#define V4L2_CID_CAMERA_FACE_DETECTION_DIRECTION (V4L2_CID_PRIVATE_BASE + 299) 

/*
  * for multi capture
*/
#define V4L2_CID_CAMERA_MULTI_CAPTURE 					(V4L2_CID_PRIVATE_BASE + 261) 
#define V4L2_CID_CAMERA_WAIT_MULTI_CAPTURE 				(V4L2_CID_PRIVATE_BASE + 262)
#define V4L2_CID_CAMERA_MULTI_CAPTURE_READY 			(V4L2_CID_PRIVATE_BASE + 263) 
#define V4L2_CID_CAMERA_MULTI_CAPTURE_PICTURE 			(V4L2_CID_PRIVATE_BASE + 264) 

/*
  * for exif information 
*/
#define V4L2_CID_CAMERA_EXIF_EXPTIME_NUMERATOR 		(V4L2_CID_PRIVATE_BASE + 271) 
#define V4L2_CID_CAMERA_EXIF_EXPTIME_DENUMINATOR 		(V4L2_CID_PRIVATE_BASE + 272) 
#define V4L2_CID_CAMERA_EXIF_TV_NUMERATOR 				(V4L2_CID_PRIVATE_BASE + 273) 
#define V4L2_CID_CAMERA_EXIF_TV_DENUMINATOR 			(V4L2_CID_PRIVATE_BASE + 274) 
#define V4L2_CID_CAMERA_EXIF_AV_NUMERATOR 				(V4L2_CID_PRIVATE_BASE + 275) 
#define V4L2_CID_CAMERA_EXIF_AV_DENUMINATOR 			(V4L2_CID_PRIVATE_BASE + 276) 
#define V4L2_CID_CAMERA_EXIF_BV_NUMERATOR 				(V4L2_CID_PRIVATE_BASE + 277) 
#define V4L2_CID_CAMERA_EXIF_BV_DENUMINATOR 			(V4L2_CID_PRIVATE_BASE + 278) 
#define V4L2_CID_CAMERA_EXIF_EBV_NUMERATOR 				(V4L2_CID_PRIVATE_BASE + 279) 
#define V4L2_CID_CAMERA_EXIF_EBV_DENUMINATOR 			(V4L2_CID_PRIVATE_BASE + 280) 
#define V4L2_CID_CAMERA_EXIF_ISOV 							(V4L2_CID_PRIVATE_BASE + 281) 
#define V4L2_CID_CAMERA_EXIF_FLASHV 						(V4L2_CID_PRIVATE_BASE + 282) 
#define V4L2_CID_CAMERA_EXIF_SDRV 						(V4L2_CID_PRIVATE_BASE + 283) 
#define V4L2_CID_CAMERA_EXIF_QV 							(V4L2_CID_PRIVATE_BASE + 284) 

/* 
  * for raw capture control
*/
#define V4L2_CID_CAMERA_RAW_IMAGE_INDEX 				(V4L2_CID_PRIVATE_BASE + 293) 
#define V4L2_CID_CAMERA_RAW_IMAGE_FLAG 					(V4L2_CID_PRIVATE_BASE + 294) 

/*other*/
#define V4L2_CID_CAMERA_CAPTURE_SIZE 					(V4L2_CID_PRIVATE_BASE + 290) 
#define V4L2_CID_CAMERA_ISP_REVERSE 						(V4L2_CID_PRIVATE_BASE + 291) 
#define V4L2_CID_CAMERA_ISP_MIRROR 						(V4L2_CID_PRIVATE_BASE + 292) 
#define V4L2_CID_CAMERA_FOCUS_WINDOW					(V4L2_CID_PRIVATE_BASE+130)
#define V4L2_CID_CAMERA_ROTATION							(V4L2_CID_PRIVATE_BASE+131)

/* 
  * for color bar function, used by factory test mode 
*/
#define V4L2_CID_CAMERA_COLORBAR							(V4L2_CID_PRIVATE_BASE + 295) 

/*
  * for scene exposure, used to determine auto focus
*/
#define V4L2_CID_CAMERA_SCENE_EV 							(V4L2_CID_PRIVATE_BASE + 296) 

/*
  * quick capture, compression
*/
#define V4L2_CID_CAMERA_QUICK_CAPTURE 					(V4L2_CID_PRIVATE_BASE + 297) 
#define V4L2_CID_CAMERA_COMPRESSION		 				(V4L2_CID_PRIVATE_BASE + 298)

#define V4L2_CID_CAMERA_WAKEUP_PREVIEW (V4L2_CID_PRIVATE_BASE + 300)
#define V4L2_CID_CAMERA_CAPTURE_FORMAT (V4L2_CID_PRIVATE_BASE + 301)

/*
* From this we can know whether light on is needed
*/
#define V4L2_CID_CAMERA_LIGHT_INFO (V4L2_CID_PRIVATE_BASE + 302)
/*
* This controls touch AF/AE
*/
#define V4L2_CID_CAMERA_SET_TOUCH_AF_AE (V4L2_CID_PRIVATE_BASE + 303)
#define V4L2_CID_CAMERA_SET_TOUCH_AE_STRENGTH (V4L2_CID_PRIVATE_BASE + 304)
#define V4L2_CID_CAMERA_SET_AF_RANGE_MODE (V4L2_CID_PRIVATE_BASE + 305)
#define V4L2_CID_CAMERA_NOW_BV (V4L2_CID_PRIVATE_BASE + 306)
#define V4L2_CID_CAMERA_PREFLASH (V4L2_CID_PRIVATE_BASE + 307)
#define V4L2_CID_CAMERA_MAINFLASH (V4L2_CID_PRIVATE_BASE + 308)
#define V4L2_CID_CAMERA_AUTO_BRACKET_CAPTURE (V4L2_CID_PRIVATE_BASE + 309)
#define V4L2_CID_CAMERA_NOW_GAIN (V4L2_CID_PRIVATE_BASE + 310)
#define V4L2_CID_CAMERA_NOW_EXPOSURE (V4L2_CID_PRIVATE_BASE + 311)
#define V4L2_CID_CAMERA_AE_LOCK (V4L2_CID_PRIVATE_BASE + 312)
#define V4L2_CID_CAMERA_AWB_LOCK (V4L2_CID_PRIVATE_BASE + 313)
#define V4L2_CID_CAMERA_FPS (V4L2_CID_PRIVATE_BASE + 314)
#define V4L2_CID_MANUAL_FOCUS_SETTING (V4L2_CID_PRIVATE_BASE + 315)
#define V4L2_CID_MANUAL_FOCUS_PERCENTAGE (V4L2_CID_PRIVATE_BASE + 316)
#define V4L2_CID_FLICKER_MODE (V4L2_CID_PRIVATE_BASE + 317)
#define V4L2_CID_CAMERA_FOCUS_POSITION (V4L2_CID_PRIVATE_BASE + 318)
#define V4L2_CID_M_SLOW_SHUT (V4L2_CID_PRIVATE_BASE + 319)
#define V4L2_CID_CAMERA_SHAPNESS (V4L2_CID_PRIVATE_BASE + 320)
#define V4L2_CID_CAMERA_CHROMA (V4L2_CID_PRIVATE_BASE + 321)
#define V4L2_CID_CAMERA_CAF_SCENARIO (V4L2_CID_PRIVATE_BASE + 322)

/* 
  * for VIDIOC_G_EXT_CTRLS and VIDIOC_S_EXT_CTRLS, from offset 0x9000 
*/
#define V4L2_CTRL_CLASS_CAMERA_BASE 			(V4L2_CTRL_CLASS_CAMERA + 0x9000)

/* 
  * for register 
*/
#define V4L2_CTRL_CLASS_CAMERA_REGISTER 		(V4L2_CTRL_CLASS_CAMERA_BASE + 1)  

/* 
  * for exif 
*/
#define V4L2_CTRL_CLASS_CAMERA_EXPTIME_N 	(V4L2_CTRL_CLASS_CAMERA_BASE + 2)    /* NUMERATOR*/
#define V4L2_CTRL_CLASS_CAMERA_EXPTIME_D 	(V4L2_CTRL_CLASS_CAMERA_BASE + 3)   /* DENUMINATOR */
#define V4L2_CTRL_CLASS_CAMERA_TV_N 			(V4L2_CTRL_CLASS_CAMERA_BASE + 4)
#define V4L2_CTRL_CLASS_CAMERA_TV_D 			(V4L2_CTRL_CLASS_CAMERA_BASE + 5)
#define V4L2_CTRL_CLASS_CAMERA_AV_N 			(V4L2_CTRL_CLASS_CAMERA_BASE + 6)
#define V4L2_CTRL_CLASS_CAMERA_AV_D 			(V4L2_CTRL_CLASS_CAMERA_BASE + 7)
#define V4L2_CTRL_CLASS_CAMERA_BV_N 			(V4L2_CTRL_CLASS_CAMERA_BASE + 8)
#define V4L2_CTRL_CLASS_CAMERA_BV_D 			(V4L2_CTRL_CLASS_CAMERA_BASE + 9)
#define V4L2_CTRL_CLASS_CAMERA_EBV_N 		(V4L2_CTRL_CLASS_CAMERA_BASE + 10)
#define V4L2_CTRL_CLASS_CAMERA_EBV_D 		(V4L2_CTRL_CLASS_CAMERA_BASE + 11)
#define V4L2_CTRL_CLASS_CAMERA_ISO 			(V4L2_CTRL_CLASS_CAMERA_BASE + 12)
#define V4L2_CTRL_CLASS_CAMERA_FLASH 			(V4L2_CTRL_CLASS_CAMERA_BASE + 13)
#define V4L2_CTRL_CLASS_CAMERA_SDR 			(V4L2_CTRL_CLASS_CAMERA_BASE + 14)
#define V4L2_CTRL_CLASS_CAMERA_QV 			(V4L2_CTRL_CLASS_CAMERA_BASE + 15)

/*
  * scane mode
*/
enum ms2r_scene_mode {
	MS2R_SCENE_NONE,
	MS2R_SCENE_AUTO,
	MS2R_SCENE_PORTRAIT,
	MS2R_SCENE_LANDSCAPE,
	MS2R_SCENE_SPORTS,
	MS2R_SCENE_NIGHTSHOT,
	MS2R_SCENE_SUNSET,
	MS2R_SCENE_MICRO,
	MS2R_SCENE_CHARACTER,
	MS2R_SCENE_MAX,
};

/*
  * flash mode
*/
enum ms2r_flash_mode {
	MS2R_FLASH_OFF,
	MS2R_FLASH_AUTO,
	MS2R_FLASH_ON,
	MS2R_FLASH_MAX,
};

/*
  * brightness value
*/
enum ms2r_ev_mode {
	MS2R_EV_MINUS_2 = 0,
	MS2R_EV_MINUS_1_5 = 1,
	MS2R_EV_MINUS_1 = 2,
	MS2R_EV_MINUS_0_5 = 3,
	MS2R_EV_DEFAULT = 4,
	MS2R_EV_PLUS_0_5 = 5,
	MS2R_EV_PLUS_1 = 6,
	MS2R_EV_PLUS_1_5 = 7,
	MS2R_EV_PLUS_2 = 8,
	MS2R_EV_MAX,
};

/*
  * white balance
*/
enum ms2r_wb_mode {	
	MS2R_WB_AUTO,
	MS2R_WB_INCANDESCENT,
	MS2R_WB_FLUORESCENT_HIGH,
	MS2R_WB_FLUORESCENT_LOW,
	MS2R_WB_SUNNY,
	MS2R_WB_CLOUDY,
	MS2R_WB_SHADE,
	MS2R_WB_HORIZON,
	MS2R_WB_MAX,
};

/*
  * effect mode
*/
enum ms2r_effect_mode {
	MS2R_IE_NONE,
	MS2R_IE_BNW,
	MS2R_IE_SEPIA,
	MS2R_IE_RED,
	MS2R_IE_GREEN,
	MS2R_IE_BLUE,
	MS2R_IE_PINK,
	MS2R_IE_YELLOW,	
	MS2R_IE_PURPLE,	
	MS2R_IE_ANTIQUE,
	MS2R_IE_MAX,
};

/*
  * iso mode
*/
enum ms2r_iso_mode {
	MS2R_ISO_AUTO,
	MS2R_ISO_50,
	MS2R_ISO_100,
	MS2R_ISO_200,
	MS2R_ISO_400,
	MS2R_ISO_800,
	MS2R_ISO_1600,
	MS2R_ISO_3200,
	MS2R_ISO_MAX,
};

/*
  * contrast mode
*/
enum ms2r_contrast_mode {
	MS2R_CONTRAST_MINUS_4,
	MS2R_CONTRAST_MINUS_3,		
	MS2R_CONTRAST_MINUS_2,
	MS2R_CONTRAST_MINUS_1,
	MS2R_CONTRAST_DEFAULT,
	MS2R_CONTRAST_PLUS_1,
	MS2R_CONTRAST_PLUS_2,
	MS2R_CONTRAST_PLUS_3,
	MS2R_CONTRAST_PLUS_4,
	MS2R_CONTRAST_MAX,
};

/*
  * wdr mode
*/
enum ms2r_wdr_mode {
	MS2R_WDR_OFF,
	MS2R_WDR_LOW,	
	MS2R_WDR_MIDDLE,
	MS2R_WDR_HIGH,
	MS2R_WDR_AUTO,
	MS2R_WDR_MAX,
};

/*
  * zoom level
*/
enum ms2r_zoom_level {
	MS2R_ZL_1 = 0x01,
	MS2R_ZL_70 = 0x46,
	MS2R_ZL_MAX,
};

/*
  * focus mode
*/
enum ms2r_focusmode {
	MS2R_FOCUS_AUTO,
	MS2R_FOCUS_MACRO,
	MS2R_FOCUS_MACRO_CAF,
	MS2R_FOCUS_FD,
	MS2R_FOCUS_FD_CAF,
	MS2R_FOCUS_TOUCH,
	MS2R_FOCUS_TOUCH_CAF,
	MS2R_FOCUS_AUTO_CAF,
	MS2R_FOCUS_MAX,
};

/*
  * frame rate
*/
enum ms2r_frame_rate {
	MS2R_FR_AUTO = 0,
	MS2R_FR_7 = 7,
	MS2R_FR_15 = 15,
	MS2R_FR_30 = 30,
	MS2R_FR_60 = 60,
	MS2R_FR_120 = 120,
	MS2R_FR_MAX,
};


enum ms2r_foucs_window {
	MS2R_MIN_WINDOW = 0,//7X7 array
	MS2R_MAX_WINDOW = 48,//7X7 array
};

/*
  * rotation
*/
enum ms2r_cam_rotation {
	MS2R_ROTATE_0,
	MS2R_ROTATE_90,
	MS2R_ROTATE_180,
	MS2R_ROTATE_270,
	MS2R_ROTATE_MAX,
};

/*
  * mirror mode
*/
enum ms2r_mirror_mode {
	MS2R_NO_MIRROR,
	MS2R_MIRROR,
	MS2R_MIRROR_MAX,
};

/*
  * mirror mode
*/
enum ms2r_reverse_mode {
	MS2R_NO_REVERSE,
	MS2R_REVERSE,
	MS2R_REVERSE_MAX,
};

#endif
